# Generated by Django 4.0.6 on 2023-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_rename_bookedby_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
