# Generated by Django 4.0.6 on 2023-02-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_favorise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorise',
            name='favori',
        ),
    ]
